name: make-docker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '37 1 4,18 * *' #build bi-weekly

jobs:
  login:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: stremio-server

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  workflow-keepalive:
      if: github.event_name == 'schedule'
      runs-on: ubuntu-latest
      permissions:
        actions: write
      steps:
        - uses: liskin/gh-workflow-keepalive@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
